version: '2'
services:
  quack:
    image: greatbit/quack
    ports:
      - "80:80"
    links:
      - mongod:mongod
    depends_on:
      - mongod
    environment:
      WAIT_HOSTS: mongod:27017
  mongod:
    container_name: "mongod"
    image: mongo:5
    expose:
      - "27017"
    ports:
      - "27017:27017"